spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
  application:
    name: jobs

logging:
  level:
    org:
      springframework:
        web=DEBUG

springdoc:
  default-produces-media-type: application/json

server:
  servlet:
    context-path: /api/v1/


  # Actuator Config
  #  management.endpoints.web.exposure.include=*
  #  management.endpoint.health.show-details=always

  #  info.app.name=Jobs API
  #  info.app.description=Application for allowing users to see job listings and for companies to list their job openings
  #  info.app.version=0.0.1
  # Allows the info details to be shown in the actuator/info endpoint
  #  management.info.env.enabled=true

  # should not be set for production apps
#  management.endpoint.shutdown.enabled=true
#  server.shutdown=graceful
